---
# INSTALL .: `pre-commit install`
# UPDATE ..: `pre-commit autoupdate`
exclude: |
  (?x)^(
    CHANGELOG\..*|
    .+\.min\.(css|js)|
    .+\.svg
  )$
default_language_version:
  python: python3.11
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  # General
  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Whitespace
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      # VCS
      - id: check-merge-conflict
        args:
          - "--assume-in-merge"
      # Config / Data Files (syntax check only)
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      # Python
      - id: debug-statements
      # Sensible Data
      - id: detect-private-key
  # Markdown
  # https://github.com/executablebooks/mdformat
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-config
          - mdformat-frontmatter
          - mdformat-mkdocs
          - mdformat-tables
        # skip linting Hugo content b/c of this bug:
        # https://github.com/executablebooks/mdformat/issues/402
        exclude: ^site/content/.*
  # Files: prevent `.rej` files (Copier merge conflicts)
  - repo: local
    hooks:
      - id: forbidden-files
        name: prevent files from being commited in git
        entry: found Copier update rejection files; review and remove them
        language: fail
        files: "\\.rej$"
  # ensure consistent formatting
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
